"""Seed a dedicated ADHD Hub memory forge repo (README + helpers)."""

from __future__ import annotations

from typing import Any

from adhd_hub.forge.config import ForgeConfig
from adhd_hub.forge.wiki_sync import WikiForgeSync


def _hub_section(hub_ui_url: str | None) -> str:
    if hub_ui_url:
        ui = hub_ui_url.rstrip("/")
        if not ui.endswith("/ui"):
            ui = f"{ui}/ui"
        return (
            "## Open the hub\n\n"
            f"**Live dashboard:** [{ui}]({ui})\n\n"
            "That UI is the source of truth for open threads, progress, and forge sync — "
            "this repo is the mirror.\n"
        )
    return (
        "## Open the hub\n\n"
        "Set `ADHD_HUB_PUBLIC_URL` (or **Hub public URL** in forge settings) to the "
        "reachable hub base (e.g. `http://100.x.x.x:8787`), then Sync again so this "
        "README links to `/ui`.\n"
    )


def primary_repo_files(*, hub_ui_url: str | None = None) -> dict[str, str]:
    readme = f"""# ADHD Hub memory

This repository is the **forge mirror** for a self-hosted **ADHD Progress Hub**.

It is **not** an application codebase. Agents and the hub write progress notes and open work here so unfinished migrations/setups survive across machines and chats.

{_hub_section(hub_ui_url)}
## Layout

| Path | Meaning |
|------|---------|
| `INDEX.md` | Open-thread index (regenerated by the hub) |
| `projects/<slug>/PROGRESS.md` | Per-project progress notes (repo root for primary memory) |
| Issues (labels `adhd-hub`, `project:<slug>`) | Optional mirror of open threads (board sync) |

## What this is / isn't

- **Yes:** markdown wiki files in-repo; optional Issues for visibility outside the hub
- **Not** a replacement for the hub dashboard (projects list, open/finished — that lives in `/ui`)
- **Not** Gitea/GitHub’s built-in Wiki feature (we use normal repo files)
- **Projects boards** are optional kanban only — set a project id in hub `/ui` if you want them

Configure sync in the hub web UI or via `ADHD_HUB_FORGE_*` env.
"""

    agents_link = ""
    if hub_ui_url:
        ui = hub_ui_url.rstrip("/")
        if not ui.endswith("/ui"):
            ui = f"{ui}/ui"
        agents_link = f"\n- Hub dashboard: {ui}\n"

    agents = f"""# Agents — ADHD memory repo

This forge repo is the ADHD Progress Hub **memory mirror**.

- Prefer reading `INDEX.md` and `projects/*/PROGRESS.md` for unfinished work.
- Do not treat this as an app to build or refactor.
- Create/update progress via the hub MCP (`upsert_thread`, `upsert_progress`) so local SQLite + this mirror stay aligned.
{agents_link}"""

    gitattributes = """# Treat hub markdown as text for clean diffs
*.md text eol=lf
"""
    return {
        "README.md": readme.strip() + "\n",
        "AGENTS.md": agents.strip() + "\n",
        ".gitattributes": gitattributes.strip() + "\n",
    }


def resolve_hub_ui_url(config: ForgeConfig, fallback: str | None = None) -> str | None:
    for candidate in (config.hub_public_url, fallback):
        if candidate and str(candidate).strip():
            return str(candidate).strip().rstrip("/")
    return None


def push_primary_scaffold(
    config: ForgeConfig, *, hub_ui_url: str | None = None
) -> dict[str, Any]:
    if not (config.enabled() and config.primary_memory_repo and config.wiki_enabled):
        return {"skipped": True, "reason": "primary_scaffold_disabled"}
    url = resolve_hub_ui_url(config, hub_ui_url)
    sync = WikiForgeSync(config)
    uploaded: list[str] = []
    errors: list[str] = []
    # Scaffold lives at repo root (not under wiki_path) so README is visible on the home page.
    for rel, content in primary_repo_files(hub_ui_url=url).items():
        try:
            sync.put_file_at_repo_root(rel, content, f"adhd-hub: seed {rel}")
            uploaded.append(rel)
        except Exception as exc:  # noqa: BLE001
            errors.append(f"{rel}: {exc}")
    return {"uploaded": uploaded, "errors": errors, "hub_ui_url": url}
